# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spade/Data_Structure/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spade/Data_Structure/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spade/Data_Structure/src/CMakeFiles /home/spade/Data_Structure/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spade/Data_Structure/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a.out

# Build rule for target.
a.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a.out
.PHONY : a.out

# fast build rule for target.
a.out/fast:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/build
.PHONY : a.out/fast

linearlist.o: linearlist.cpp.o

.PHONY : linearlist.o

# target to build an object file
linearlist.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/linearlist.cpp.o
.PHONY : linearlist.cpp.o

linearlist.i: linearlist.cpp.i

.PHONY : linearlist.i

# target to preprocess a source file
linearlist.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/linearlist.cpp.i
.PHONY : linearlist.cpp.i

linearlist.s: linearlist.cpp.s

.PHONY : linearlist.s

# target to generate assembly for a file
linearlist.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/linearlist.cpp.s
.PHONY : linearlist.cpp.s

queue.o: queue.cpp.o

.PHONY : queue.o

# target to build an object file
queue.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/queue.cpp.o
.PHONY : queue.cpp.o

queue.i: queue.cpp.i

.PHONY : queue.i

# target to preprocess a source file
queue.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/queue.cpp.i
.PHONY : queue.cpp.i

queue.s: queue.cpp.s

.PHONY : queue.s

# target to generate assembly for a file
queue.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/queue.cpp.s
.PHONY : queue.cpp.s

stack.o: stack.cpp.o

.PHONY : stack.o

# target to build an object file
stack.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/stack.cpp.o
.PHONY : stack.cpp.o

stack.i: stack.cpp.i

.PHONY : stack.i

# target to preprocess a source file
stack.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/stack.cpp.i
.PHONY : stack.cpp.i

stack.s: stack.cpp.s

.PHONY : stack.s

# target to generate assembly for a file
stack.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/stack.cpp.s
.PHONY : stack.cpp.s

start.o: start.cpp.o

.PHONY : start.o

# target to build an object file
start.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/start.cpp.o
.PHONY : start.cpp.o

start.i: start.cpp.i

.PHONY : start.i

# target to preprocess a source file
start.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/start.cpp.i
.PHONY : start.cpp.i

start.s: start.cpp.s

.PHONY : start.s

# target to generate assembly for a file
start.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/start.cpp.s
.PHONY : start.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... a.out"
	@echo "... edit_cache"
	@echo "... linearlist.o"
	@echo "... linearlist.i"
	@echo "... linearlist.s"
	@echo "... queue.o"
	@echo "... queue.i"
	@echo "... queue.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... start.o"
	@echo "... start.i"
	@echo "... start.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

